### ISSUE TITLE
Development Chore: Do something about patch state

### ISSUE THREAD

**Issue by spencerudnick** [spencerudnick/synth.kitchen#7]
To simplify the eventual work of implementing import/export, centralize a patch's state in redux.

**Comment by spencerudnick** [comment]
@stfnsr opening this so we can have a place to discuss https://github.com/spencerudnick/synth.kitchen/pull/6.

**Comment by spencerudnick** [comment]
Since we're eventually moving toward patches being used as part of tutorials, it makes sense to consider the root component (currently Kitchen) a "Patch". This makes more sense to me as a name, as we're talking about storing the patch state in redux in the root of what is currently the app.

This could potentially enable the Patch to be used as a module on its own, which seems to answer the question of how to handle state for nested modules.

Given this, does it make sense to continue using Redux? The alternative would be to use React's state and Context APIs, which come with the framework.

I understand the attraction of Redux dev-tools but they may be overkill if we can instead clean up the state-management.

**Comment by stfnsr** [comment]
> Since we're eventually moving toward patches being used as part of tutorials, it makes sense to consider the root component (currently Kitchen) a "Patch". This makes more sense to me as a name, as we're talking about storing the patch state in redux in the root of what is currently the app.
I think it makes sense if what we're building is a component, as opposed to building the whole app.

> Given this, does it make sense to continue using Redux? The alternative would be to use React's state and Context APIs, which come with the framework.
The appeal of Redux for me lies in the available middleware (like redux-saga asynchronous and/or impure things), as well as in having all (relevant) state in one place. It might not be neccessary, but from what i understand it provides a clear path for most problems, compared to relying on useReducer/useContext alone.
That said, the devtools are pretty nifty.

I think nested modules should not be too problematic even in a centralized store. With the added advantages of having all the data neatly normalized. Will draw something up.

Oh, also:
Redux and diy/useReducer aren't the only options anyway.
I keep hearing good things about MobX, have you ever looked into it?

**Comment by spencerudnick** [comment]
> I think it makes sense if what we're building is a component, as opposed to building the whole app.
We are building an app. But my thought is it may be productive on the way to building the app to reframe the current Kitchen as a Patch.

> compared to relying on useReducer/useContext alone
We don't even have to use these APIs; I'm a fan of passing state through the channels built into React.

I looked at MobX, but again I'm not sure what this accomplishes outside of neatly defining state (and transformations of it) inside the components that need it.
